CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++11

all: prob1 prob2

prob1: prob1.cpp
	$(CXX) $(CXXFLAGS) -o prob1 prob1.cpp

prob2: prob2.cpp
	$(CXX) $(CXXFLAGS) -o prob2 prob2.cpp

clean:
	rm -f prob1 prob2

.PHONY: all clean
